/**
 * Copyright 2004 CANTV. All rights reserved.
 * CANTV PROPRIETARY/CONFIDENTIAL. Use is subject to license
 * terms.
 * <p>
 * This software is the confidential and proprietary information
 * of CANTV. ("Confidential Information"). You shall not
 * disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered
 * into with CANTV.
 * <p>
 * Creation date: 2004-12-20
 */
package ve.com.cantv.common.hera.logging;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * Class LoggingConfigurator
 * <p>
 * This class prints the log config files used to properly visualize the logs files generated by the Cantv Logging Framework.
 * Besides, LoggingConfigurator is used to retrieve the configuration information from hera-logging.properties file.
 * In case of this file cannot be found and loaded, the Cantv Logging Framework will be use the following default values:
 * <p>
 * To define the underlying UniversalLogger class:
 * loggingClass=ve.com.cantv.sgcc.util.logging.Log4JLogger
 * <p>
 * To define the logging format date used in the log file:
 * loggingFormatDate=yyyy-MM-dd HH:mm:ss.SSS
 * <p>
 * Note: This class used the stdout standard because the Cantv Logging Framework has not been initialized yet.
 *
 * @author Liodegar Bracamonte
 */
public final class LoggingConfigurator {

    /**
     * The base name to build the ResourceBundle object used for logging configuration.
     */
    public static final String HERA_LOGGING_NAME = "hera-logging";

    /**
     * Optional key defined in <code>hera-logging.properties</code> to indicate the full qualified class name
     * of your UniversalLogger class. This value is declared here, in order to avoid circular references
     * with CantvProperty class.
     */
    public static final String LOGGING_CLASS_NAME = "loggingClass";



    /**
     * The private modifier is to avoid the instantiation outside this class
     */
    private LoggingConfigurator() {
    }

    /**
     * Gets a string for the given key from <code>hera-logging.properties</code>.
     *
     * @param key the key for the desired string
     * @return the string for the given key or null if no object for the given key can be found
     * @throws java.lang.NullPointerException if <code>key</code> is <code>null</code>
     */
    public static String getString(String key) {
        return getString(key, HERA_LOGGING_NAME);
    }

    /**
     * Gets a string for the given key from <code>hera-logging.properties</code>.
     *
     * 
     * @return the string for the given key or null if no object for the given key can be found
     * @throws java.lang.NullPointerException if <code>key</code> is <code>null</code>
     */
    public static String getLoggingClassName() {
        return getString(LOGGING_CLASS_NAME);
    }


    /**
     * Gets a string for the given key using the ResourceBundle object.
     *
     * @param key      the key for the desired string
     * @param baseName the base name of the resource bundle, a fully qualified class name
     * @return the string for the given key or null if no object for the given key can be found
     */
    private static String getString(String key, String baseName) {
        try {
            ResourceBundle bundle = getProperties(baseName);
            if (bundle == null) {
                System.out.println(
                        "LoggingConfigurator.getString().The "
                                + baseName
                                + ".properties cannot be retrieved. The default conf info will be used.");
                return null;
            }
            return bundle.getString(key);
        } catch (MissingResourceException e) {
            System.out.println(new StringBuilder(100).append("LoggingConfigurator.getString() Missing this key:'")
                    .append(key).append("' in ").append(baseName).append(".properties").toString());
            return null;
        }
    }

    /**
     * Gets a resource bundle using the specified base name
     *
     * @param baseName the base name of the resource bundle, a fully qualified class name
     * @return The ResourceBundle object if a resource bundle for the specified base baseName can be found, otherwise returns null.
     */
    private static ResourceBundle getProperties(String baseName) {
        try {
            return ResourceBundle.getBundle(baseName);
        } catch (Exception e) {
            System.out.println("LoggingConfigurator.getProperties(). The " + baseName + ".properties cannot be loaded.");
            return null;
        }
    }

}
